import Head from "next/head";

import Header from "@/components/Header";
import styles from "../styles/Layout.module.css";
import Footer from "@/components/Footer";

const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title> {title}  || </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <Header />
        {children}
        <Footer />
      </main>
    </>
  );
};
export default Layout;
